[package]
name = "sessions_smart_contract"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"
openzeppelin_account = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }

[dev-dependencies]
snforge_std = "0.54.1"

[[target.starknet-contract]]
sierra = true
casm = true
