[package]
name = "sessions_smart_contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v2.0.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "scarb test"
build = "scarb build"

